### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by aksa111** [saurfang/rwebhdfs#11]
With `write_file` from local connected to VPN, returns error
`> write_file(hdfs, file, foo)
Error in function (type, msg, asError = TRUE)  : 
  Could not resolve host: <hostname>
`

But, the same command works on the server.  What would be the issue?

**Comment by antbbn** [comment]
Could you provide the code you use to create the `hdfs` object?

**Comment by aksa111** [comment]
@antbbn It got resolved.  I had to add the hosts in `etc/hosts`
